name: Run Legitify (Binary)
on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  statuses: write

jobs:
  run_legitify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Run Legitify"
        shell: bash 
        run: |
          ./legitify --token ${{ secrets.LEGITIFY_GITHUB_PAT }} analyze --repo ruudgoossens/test-legitify --output-format sarif --output-file results.sarif
      - name: "Upload SARIF results"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
